version: "3"

services:
  db:
    container_name: wps-db
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  app:
    container_name: wps-app
    depends_on:
      - db
    build:
      context: ./docker/wordpress
    volumes:
      - ./app:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      MYSQL_PWD: wordpress
    env_file:
      - wp-sandbox.env
